- name: Deploy Odoo with Docker in EC2 instance
  hosts: all
  become: true

  tasks:
    - name: Copy private SSH key to server (temporary)
      ansible.builtin.copy:
        src: id_ed25519
        dest: /root/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Fetch repo updates
      ansible.builtin.git:
        repo: git@github.com:Experts-Vision/ev-odoo-basic.git
        dest: /home/ubuntu/ev-odoo-basic
        version: HEAD
        update: yes
        force: yes

    - name: Remove private SSH key after use
      ansible.builtin.file:
        path: /root/.ssh/id_rsa
        state: absent

    - name: Clean up (Remove all Docker containers & images)
      ansible.builtin.shell: |
        containers=$(docker ps -aq)
        if [ -n "$containers" ]; then
          docker stop $containers
          docker rm -f $containers
        else
          echo "No containers to remove."
        fi
        docker image prune -a -f

    - name: Build Docker containers
      shell: docker compose -f /home/ubuntu/ev-odoo-basic/run-profiles/cloud-ubuntu/compose.yaml build

    - name: Start Docker containers
      shell: docker compose -f /home/ubuntu/ev-odoo-basic/run-profiles/cloud-ubuntu/compose.yaml up -d

